// <auto-generated />
using Currency.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Currency.Migrations
{
    [DbContext(typeof(CurrencyContext))]
    [Migration("20220208052342_Intial")]
    partial class Intial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Currency.Models.Currency", b =>
                {
                    b.Property<int>("CurrencyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyFullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrevRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CurrencyID");

                    b.ToTable("Currency");

                    b.HasData(
                        new
                        {
                            CurrencyID = 1,
                            CurrencyCode = "USD",
                            CurrencyFullName = "US Dollar",
                            PrevRate = 40694.543m,
                            Rate = 40694.543m,
                            Unit = "$"
                        },
                        new
                        {
                            CurrencyID = 2,
                            CurrencyCode = "BTC",
                            CurrencyFullName = "Bitcoin",
                            PrevRate = 1.0m,
                            Rate = 1.0m,
                            Unit = "BTC"
                        },
                        new
                        {
                            CurrencyID = 3,
                            CurrencyCode = "PHP",
                            CurrencyFullName = "Philipine Peso",
                            PrevRate = 2083596.208m,
                            Rate = 2083596.208m,
                            Unit = "₱"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
